### ISSUE TITLE
Unable to re-login to the same account from different browser

### ISSUE THREAD

**Issue by jellohouse** [Glench/ExtPay#108]
**Describe the bug**
I'm unable to re-login to the same ExtPay account from a different browser.
Using my developer login (should be free). 

**To Reproduce**

If I try to login with my email it says: `Sorry, we don't have that email in our records. Please try another or contact the extension developer.`

If I try to sign up with the same email it says: `That email has already been used.`

**Expected behavior**
It should work as before - I should be able to login with the same email I've signed up with before (especially dev email).

**Comment by jellohouse** [comment]
Right sorry I forgot to mention this only happens in the published version. 
Login works fine in development version.

But maybe I'm misunderstanding something - in the published version once you sign up (in my case for a free trial period) should you be able to go to another browser, install the extension and use the same login email you signed up with? My thought was that yes.

**Comment by henriquesousapt** [comment]
We are also facing this issue, if we re-install the extension and try to resume a trial with an email that is still in the trial period, it returns the following error:

<img width="612" alt="Screenshot 2023-03-17 at 16 54 07" src="https://user-images.githubusercontent.com/61880217/225969541-31f2835d-f6b1-45ba-b258-3025e1e54a57.png">

In this case the trial should be resumed, since it's still within the trial period.

Is it possible to have this behavior?

**Comment by Glench** [comment]
Ah, thank you both for the clarity! You're right, it would be a good feature to "resume" a free trial from a different device or chrome profile.

**Comment by henriquesousapt** [comment]
@Glench do you think this feature could be implemented soon?

**Comment by vuciv** [comment]
Hey, just wanted to say this is still the case.

**Comment by Glench** [comment]
So, we've added this! 

Users can now log in to an existing trial. Their `trialStartedAt` will be the same after they log in. This means users will no longer see an error message saying they've already started a trial if they attempt to put the same email in twice. It's up to you to show appropriate messages if they log in and their trial period is over.

Cheers!
