### ISSUE TITLE
is this stripe payment only

### ISSUE THREAD

**Issue by test2a** [Glench/ExtPay#11]
hi. i would like to know if a third party payment gateway can be used with this instead of stripe? because stripe is not available in many place

**Comment by Glench** [comment]
Currently it's only Stripe. Paypal is also planned. Which other services are you thinking of?

**Comment by test2a** [comment]
india has many gateways like https://razorpay.com/docs/
https://docs.instamojo.com/

**Comment by Glench** [comment]
Cool, thanks for letting me know. Have you tried signing up for Stripe via ExtensionPay? It works in India now. I have at least one Indian developer who's using it successfully.

**Comment by test2a** [comment]
@glench interesting. i did not know stripe was available in india. this should be interesting then. the 5+2% is interesting but manageable. if i am able to get stripe working for me, i will definitely start with the integration. will ask for support if anything crops up

**Comment by Glench** [comment]
ok great!

**Comment by test2a** [comment]
@Glench extensionpay.com asks me for USD only. do we have some way to make it in other currencies or do i write in USD and the stripe pays in INR?

**Comment by Glench** [comment]
Yes, Stripe pays in INR. I'm still working out a good way of dealing with currencies.

**Comment by test2a** [comment]
@Glench  so i write say USD 10 in extensionpay and it would translate the same into INR. that is what i understand. is that right?
what about if i want to ask for more than 1 subscription plan, like $10 plan and $20 plan?

**Comment by Glench** [comment]
Exactly — you get paid in INR even though the currency shows to the customer as USD.

At the moment there is only support for one plan per extension although that will be changing soon!

**Comment by test2a** [comment]
@Glench when i try to connect glench, it is asking to create a new business which fails because it says contact support
 it shouldnt do as i have created  a new business "in india"

**Comment by Glench** [comment]
Can you email me? glen@extensionpay.com

**Comment by test2a** [comment]
@glench i have emailed you.

**Comment by test2a** [comment]
@glench i see the stripe has very limited payment options in india, only visa/mastercard when there are multiple other means (netbanking, Rupay, UPI, wallets etc) for indian customers. i have a question, if i have a customer wanting to pay me by any other means and i accept the payment, is there a way to activate the extensionpay for them from backend? i understand stripe says yes to them then extensionpay accepts that. 
i tried to to adjust balance then manually adjusting the amount to give them credit but i havent tested if extensionpay sees that so do you have an idea what would be the case?

**Comment by Glench** [comment]
Hm good to know!

At the moment users can email me with the customers they want to add and I
can mark them as paid. The reason it's like this so far is to prevent the
situation you're describing where a developer uses the ExtensionPay service
but takes payments through other means so doesn't end up paying for the
service. However, because I want to support other payment services like
Paypal and maybe RazorPay it seems like I'll want to change things around a
little bit.

In the meantime I'm happy to work something out with you if you'd like.
Please email me so we can work out the details.

**Comment by test2a** [comment]
@glench OK. That is a valid reason and I understand that but I can cone up with 2 issues. 1. Base currency fluctuation. Like I put usd but I am selling in inr so my inr value should be fixed and not usd. Base currency should be changeable because I cannot advertise $10 when it translates to inr 750 today and paid 760 tomorrow.

2. I dont mind paying for your service as long as I dont have to build this infra myself, I am saving me that hassle so there is that. I have an idea. Why dont you raise an invoice for all endries that didnt go through you, like lets say I have a customer for who I received cash, well when I go and manually add that user as paid, your software would charge me the commission separately. That way you are paid and I dont have to keep buzzing you. I mean thats one idea. 

Ps, can you bring referral system or some "codes" which can be pre paid discounts? That would make the social gamification of extension and help get more customers. Just a small feature request

**Comment by Glench** [comment]
>1. Base currency fluctuation.

The problem with selling in INR is that I believe most cards around the world can't pay in this currency, which alienates most of the worldwide users. Furthermore, selling in a currency that a user isn't familiar with decreases sales significantly according to most of the data I've seen. The Google and Apple app stores solve this by having pricing "tiers" that have equivalent amounts in different currencies and they show the user their local currency. This is one approach I'm considering. It doesn't solve the issue of fluctuating currency prices that you mentioned but if it's good enough for the app stores I think it should work for ExtensionPay. I mostly just haven't had time to implement it yet. In the meantime, the developers using ExtensionPay so far have been quite successful selling in just USD.

>2. Why dont you raise an invoice for all endries that didnt go through you

Like I said, email me and we can work something out — I'm flexible here. ExtensionPay is still a newish service and I'm working out the right pricing. Discount codes are definitely coming too!

**Comment by test2a** [comment]
@glench that is where i suppose the "account country" comes in for stripe. i understand it accepts a base country for an account like it did mine for india and set INR as base currency and the requisite taxes. can you see if extensionpay can recognise 
"Charges for a currency without a bank account will be converted to your default currency, INR." which is in settings, payout settings ? or something like this ? https://stripe.com/docs/api/country_specs/object#country_spec_object-default_currency

i don't know, i am still new to stripe and monetization.  from what i understand, apple and google have standard conversion rates so 75 INR is 1 US$ regardless of actual currency translation. they absorb the cost/benefit so that customers get a standard price. that is why app store prices are equal but standard in countries. like in USA, apple will show $10 and in india, it will show INR 750 regardless of what fluctuation is. it think i read something like that. 

what i am thinking is, if i set my "country" as india, then my base price should be that and if any other currency wants to pay, stripe will translate that figure but my base currency should remain the same. 
as i said, the service looks promising enough for me to go ahead with it so yeah lets work things out together

**Comment by Glench** [comment]
Oh was that your question? Yes, regardless of what currency your customers
pay you in, you'll always receive payouts in Stripe in INR (if that's your
currency).
