### ISSUE TITLE
Error: User doesn't match extension. Are you sure you're using the right extension id in all places?

### ISSUE THREAD

**Issue by Nodirbek3d** [Glench/ExtPay#116]
**Describe the bug**
I have created an extension with id `gpt-assistant` and when I use it, getting this error on payment page:
```
Error: User doesn't match extension. Are you sure you're using the right extension id in all places?
```

**To Reproduce**
```
importScripts('./lib/ExtPay.js')

// background.js
const extpay = ExtPay('gpt-assistant')
extpay.startBackground();
extpay.getUser().then(user => {
    if (user.paid) {
        // ...
    } else {
        extpay.openPaymentPage()
    }
})
```
**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome

**Comment by Glench** [comment]
When you change the extension id you have to remove and re-add your extension in chrome.
