### ISSUE TITLE
Chrome Manifest Version 3

### ISSUE THREAD

**Issue by burkybang** [Glench/ExtPay#12]
Google has started offering support for Manifest Version 3 (MV3). I assume they will eventually phase out MV2. Your guide for how to implement ExtPay in a Chrome extension is for MV2. Have you tried MV3 yet? Are you planning on releasing a guide for that soon? My main concern is compatibility with service workers.

### Relevant Links
- [Migrating to Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/)
- [Migrating from background pages to service workers](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/)

**Comment by Glench** [comment]
Thanks for the nice feature request! As it says in the current docs, Manifest v3 support is coming soon. Seems like the next thing I'll do since I've been getting the request a lot lately.

**Comment by Glench** [comment]
This is done! 10fb572
