### ISSUE TITLE
Not able to log back in as Sample User

### ISSUE THREAD

**Issue by prakhar897** [Glench/ExtPay#128]
1. I used an alternate email to start trial of my product. 
2. Then I delete and reinstall my chrome extension. 
3. When I try to start trial again, it displays the following message "That email has already been used."
4. When I click login and try to login as my free trial is running,  it displays the following message: "Sorry, we don't have that email in our records. Please try another or contact the extension developer."

It seems the system gets in a deadlock if a trial user reinstalls the app. Can you look into it?

![Capture](https://user-images.githubusercontent.com/25222802/235265209-bddd4767-d9d0-449d-8beb-7eda860ed8ab.PNG)
![image](https://user-images.githubusercontent.com/25222802/235265170-66741175-1f35-46de-8629-58f27008514b.png)

**Comment by Glench** [comment]
Yeah, right now "log in" means for paid customers only, not trial users. It should be fixed for sure but it's not a very high priority right now.

**Comment by dm1014** [comment]
@Glench I also ran into this issue during development. It seems like the user record _should_ exist since `extpay.getUser()` works after starting a trial

**Comment by dm1014** [comment]
> @Glench is there a workaround for this? How can I login when I started a trial, but reinstalled the extension?

a possible workaround would be to alert the user to use a different email.
it's not very user-friendly though and could lead to users just starting trials with different emails

**Comment by Glench** [comment]
> As @dm1014 mentioned it's not a very user-friendly way to do this and it becomes more complicated during the development when I have to test the trail flow locally.
> 
> Every time I have to test the flow I would have to use a new email.

This is a completely separate issue. You might consider creating a new discussion for it where you discuss in detail the issue you're getting.

Also, if you use your developer email for trials in development mode you won't have to use different emails every time.

**Comment by Glench** [comment]
This has been fixed! See #108
