### ISSUE TITLE
Allow Payment in decimal Figure Please

### ISSUE THREAD

**Issue by JayJay-101** [Glench/ExtPay#13]
example like for 9.99 $ Please

**Comment by Glench** [comment]
Definitely! Just make it $10 for now until I get to it.

**Comment by Glench** [comment]
Alright, decimal display is now supported across the site. I just have to update the price change form to validate decimal figures and this will be done.

**Comment by Glench** [comment]
Okay, it's done! You can use the "Change price" link on your developer dashboard. Thanks for your patience!
