### ISSUE TITLE
What is the extension ID in signup?

### ISSUE THREAD

**Issue by egfx** [Glench/ExtPay#14]
I don't really understand what it's asking in the signup screen when it asks for the extension ID.

"A unique id for URLs and your code" is the subheading.

Is this asking for the unique webstore ID that is associated with the extension or the Full URL or is this something we can make up on our own?

**Comment by burkybang** [comment]
It's something you make up.

**Comment by Glench** [comment]
@burkybang is right! It can be whatever you like. By default it auto-fills with your extension title but lowercase and with all punctuation and spaces removed. You'll use it in your code like this:

```js
const extpay = ExtPay('my-id-here');
```

Let me know if you get stuck anywhere else!
