### ISSUE TITLE
does other any payment getway supported

### ISSUE THREAD

**Issue by seyhadot** [Glench/ExtPay#15]
I mean in my country it's not supported with a Stripe so what should I do? do you have any solution? Thank you

**Comment by Glench** [comment]
At the moment only Stripe is supported but Paypal support is planned. Do you have a preferred payment gateway that you'd like to use?

And if anyone else finds this thread in the future, please comment with the payment provider you'd like and I'll see if I can support them!

**Comment by burkybang** [comment]
+1 for PayPal

**Comment by idolize** [comment]
Hi @Glench any updates on when PayPal support is likely to land? Is it still being worked on? Thanks!

**Comment by amonam** [comment]
Hi, Any update about the release date of Paypal support?

**Comment by n0trace** [comment]
@Glench Hi, Any update about the release date of Paypal support?

**Comment by nxcoong** [comment]
Hi, Any update about the release date of Paypal support?

**Comment by iendeavor** [comment]
+1 for Paypal

**Comment by emvaized** [comment]
Any updates on PayPal support? 😊

**Comment by Lotzi-tosafix** [comment]
Hi,
I see that PayPal integration has been on the roadmap for a while now.
As a developer based in Israel, I don't have full access to Stripe (it's not supported here for local bank accounts), which makes it difficult for me to use ExtensionPay at the moment. PayPal would be a perfect solution for me.
Is there an updated expiration date or a beta version we can check out? That would be helpful for me and other international developers.
Thanks for your great work on this project!
