### ISSUE TITLE
Empty trial period initialisation shows unwanted text

### ISSUE THREAD

**Issue by Gentatsu** [Glench/ExtPay#150]
**Describe the bug**

When calling `extpay.openTrialPage` without args, it shows `[object PointerEvent] free trial.` (shown below in screenshot) instead of nothing. 

**Expected behavior**
Empty string to be shown instead

**Screenshots**
![image](https://github.com/Glench/ExtPay/assets/3910724/457c4005-e964-4343-8cae-af9e2bb93863)

**Comment by Glench** [comment]
Hm, I can't reproduce this. What browser are you using and can you send me a minimal example that demonstrates the bug?

**Comment by Gentatsu** [comment]
Am using chrome, and the latest version via npm if that helps? Will try and produce a MWE soonish.

**Comment by Glench** [comment]
You can probably just copy the sample extension in this repo to produce an example that demonstrates the problem and add in a call to the openTrialPage function.

**Comment by Glench** [comment]
Any news on this? I'll be closing the issue soon if you can't reproduce it.

**Comment by Glench** [comment]
Since it's been more than a month since I've seen a reply and there's no reproduction steps, I'm going to close this issue. Please open it back up if you can reproduce it.
