### ISSUE TITLE
User status in-consistency if user had a cancelled transaction

### ISSUE THREAD

**Issue by complanboy2** [Glench/ExtPay#162]
**Describe the bug**
If a user had cancelled the subscription some time back Or if he has a failed transaction some time ago, then the user status is coming as not paid even after he paid for the current month / have active subscription.

**To Reproduce**
1. Create (/Pick) a user and make a failed payment attempt Or cancelled payment
2. Pay the current invoice for the same user. Basically have an active subscription
3. Now, try to fetch the user's paid status

**Expected behavior**
The paid status should ideally should check for a valid transaction in the current month. Irrespective of previous failed / cancelled transactions along with current failed transactions.

**Screenshots**
All the details related to a user has been share privately (since it has PI)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
As confirmed by Glen, this has been fixed in staging. But the issue is still alive on prod. And many of the users are complaining about the same.

**Comment by Glench** [comment]
Because of the custom code we've written for you, Veera, this is only an issue for you, no one else. As such, I'm closing this issue and moving it back to email. Please keep it there.
