### ISSUE TITLE
Payment not going through

### ISSUE THREAD

**Issue by 0x48piraj** [Glench/ExtPay#171]
**Describe the bug**
The payment is not going through, I kept digging and found out you need to pass [name and billing address](https://support.stripe.com/questions/failed-international-payments-from-stripe-accounts-in-india) in order to process payments in India.

**Screenshot**
![image](https://github.com/Glench/ExtPay/assets/5800726/81636add-4b5c-4731-bbbf-c04df2cd35b1)

**Comment by Glench** [comment]
Hey Piyush, let's take care of this issue privately over email. Indian accounts have special rules that I need to enable manually for your account.
