### ISSUE TITLE
Testing onPaid.addListener throws error message

### ISSUE THREAD

**Issue by rylandstackbit** [Glench/ExtPay#181]
**Describe the bug**
After I test taking a payment, the console of the `https://extensionpay.com/extension/timewriter/subscribed/*` window shows this error message `Uncaught (in promise) message: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`. It shows after 5 or so seconds. And the code I placed inside the listener doesn't run.

**Recording**
Here's a [video recording](https://www.loom.com/share/a5e392e49b6541e884396346b059ea5f) to reproduce.

**Desktop (please complete the following information):**
 - OS: `Mac version 12.3 Monterey`
 - Browser `Chrome`
 - Version `Version 119.0.6045.199 (Official Build) (arm64)`

**Comment by Glench** [comment]
Hey, sorry for the late reply! For some reason Github stop notifying me of issues??  The onPaid listener only works in background.js for now. So move it there then send a message to the tab where your extension is running.
