### ISSUE TITLE
Test Mode == Canceled -> user.paid == true

### ISSUE THREAD

**Issue by philipmulcahy** [Glench/ExtPay#185]
**Describe the bug**
I set my ExtPay test account to Cancelled on my subscription-based extension, but the extpay client calls continue to respond with paid == true.

**To Reproduce**
1. Install "amazon order history reporter" chrome extension from chrome webstore.
2. Open a tab to amazon.com (or amazon.co.uk, .de, .fr. .ca).
3. Open the extension pop-up (orange A button).
4. Log into preview/premium features via the preview features button, using test user.
5. Set the user to have paid subscribed status.
6. Refresh the tab.
7. Open pop-up and see that there are no greyed out checkboxes on the extension's popup.
8. re-open the extpay dialog and set the test user to cancelled state.
9. refresh tab
10. reopen extension popup.
11. See paid features are still paid
12. Open background page in debugger, and put breakpoint in ExtPay.module.js where user is fetched.
13. Re-open extension popup (forces user to be fetched)
14. See user.paid == true

**Expected behavior**
Newly fetched user.paid should be false when. the test user's subscription is cancelled (?)
It used to work like this and if it doesn't then what is test mode for?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos 14.2.1
 - Browser: chrome 120.0.6099.129

**Additional context**
Here's the code I use to query ExtPay: https://github.com/philipmulcahy/azad/blob/9753074d7d18fb3da421b3c74ac05e5b6c69298c/src/js/extpay_client.ts
The extension uses webpack.

Thank you!

**Comment by Glench** [comment]
Hey Philip, it's a lot of work for me to separate what your code is doing from what is actually going on with ExtensionPay. Would you be able to create a minimal example the demonstrates the problem you're seeing and doesn't have any of your own code? Maybe you could use the sample-extension-mv3 in this repo.

**Comment by Glench** [comment]
Hey Philip, any updates on your minimal repo? If not, I'll close this issue.

**Comment by philipmulcahy** [comment]
Sorry - not yet - I’ve been chasing down some other bugs that are more urgent, but this one is going to start hurting me soon, as we’re getting closer to the year boundary.
Thanks for the chaser!

**Comment by goofedup** [comment]
> Hey Philip, it's a lot of work for me to separate what your code is doing from what is actually going on with ExtensionPay. Would you be able to create a minimal example the demonstrates the problem you're seeing and doesn't have any of your own code? Maybe you could use the sample-extension-mv3 in this repo.

I'm having pretty much the same issue but it doesn't matter what I change the status to. Here's my popup's code. It's odd as everything was working fine. I haven't even changed any code from when it was working earlier today.

```
const extpay = ExtPay('offer-sender'); 
extpay.getUser().then(user => {
    console.log(user)
    const now = new Date();
    // const sevenDays = 1000*60*60*24*7 // in milliseconds
    if (user.trialStartedAt && (now - user.trialStartedAt) < sevenDays) {
        $('header').append('<button sub>Subscribe</button>')
        $('p').text('Enjoy your free trial!')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: true
        }, function () {
        })
    } else if (user.paid && !user.subscriptionCancelAt) {
        $('header').append('<button sub>Manage Subscription</button>')
        $('p').text('Thanks for subscribing!')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: true
        }, function () {
        })
        console.log("You're paid!")
    } else if (user.paid && user.subscriptionCancelAt) {
        $('header').append('<button sub>Manage Subscription</button>')
        $('p').text('Your subscription will end at the next billing cycle.')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: true
        }, function () {
        })
        console.log("Your subscription will end at the next billing cycle")
    } else if (user.subscriptionStatus === 'past_due') {
        $('header').append('<button sub>Update Payment Info</button>')
        $('p').text('Your payment has failed.')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: false
        }, function () {
        })
        console.log("You need to update your card!");
    } else if (user.subscriptionStatus === 'canceled') {
        $('header').append('<button sub>Subscribe</button>')
        $('p').text('Your subscription has ended.')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: false
        }, function () {
        })
        console.log("We hope you enjoyed your subscription!")
    } else {
        $('header').append('<button sub>Start Free Trail / Subscribe</button><br><button log>Login</button>')
        $('[sub]').click(function(){
            extpay.openTrialPage('7-day')
        })
        $('[log]').click(function(){
            extpay.openLoginPage()
        })
        chrome.storage.local.set({
            paystatus: false
        }, function () {
        })
        console.log("You haven't paid yet :( ")
    }
})
```


![Screenshot 2024-03-28 224423](https://github.com/Glench/ExtPay/assets/66225070/a7a4e003-06b7-4bd4-8122-614cb73344eb)
![Screenshot 2024-03-28 224626](https://github.com/Glench/ExtPay/assets/66225070/0f057f88-1be9-4f75-9838-d3dcace33c0e)

**Comment by goofedup** [comment]
> Hey Philip, it's a lot of work for me to separate what your code is doing from what is actually going on with ExtensionPay. Would you be able to create a minimal example the demonstrates the problem you're seeing and doesn't have any of your own code? Maybe you could use the sample-extension-mv3 in this repo.

I'm having pretty much the same issue but it doesn't matter what I change the status to. Here's my popup's code. It's odd as everything was working fine. I haven't even changed any code from when it was working earlier today.


I'll add that I removed and reloaded the extension and logged in and confirmed my email multiple times in a single day. I don't know if this could cause this but I wouldn't think so.

```
const extpay = ExtPay('redacted'); 
extpay.getUser().then(user => {
    console.log(user)
    const now = new Date();
    // const sevenDays = 1000*60*60*24*7 // in milliseconds
    if (user.trialStartedAt && (now - user.trialStartedAt) < sevenDays) {
        $('header').append('<button sub>Subscribe</button>')
        $('p').text('Enjoy your free trial!')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: true
        }, function () {
        })
    } else if (user.paid && !user.subscriptionCancelAt) {
        $('header').append('<button sub>Manage Subscription</button>')
        $('p').text('Thanks for subscribing!')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: true
        }, function () {
        })
        console.log("You're paid!")
    } else if (user.paid && user.subscriptionCancelAt) {
        $('header').append('<button sub>Manage Subscription</button>')
        $('p').text('Your subscription will end at the next billing cycle.')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: true
        }, function () {
        })
        console.log("Your subscription will end at the next billing cycle")
    } else if (user.subscriptionStatus === 'past_due') {
        $('header').append('<button sub>Update Payment Info</button>')
        $('p').text('Your payment has failed.')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: false
        }, function () {
        })
        console.log("You need to update your card!");
    } else if (user.subscriptionStatus === 'canceled') {
        $('header').append('<button sub>Subscribe</button>')
        $('p').text('Your subscription has ended.')
        $('[sub]').click(function(){
            extpay.openPaymentPage();
        })
        chrome.storage.local.set({
            paystatus: false
        }, function () {
        })
        console.log("We hope you enjoyed your subscription!")
    } else {
        $('header').append('<button sub>Start Free Trail / Subscribe</button><br><button log>Login</button>')
        $('[sub]').click(function(){
            extpay.openTrialPage('7-day')
        })
        $('[log]').click(function(){
            extpay.openLoginPage()
        })
        chrome.storage.local.set({
            paystatus: false
        }, function () {
        })
        console.log("You haven't paid yet :( ")
    }
})
```


![Screenshot 2024-03-28 224423](https://github.com/Glench/ExtPay/assets/66225070/a7a4e003-06b7-4bd4-8122-614cb73344eb)
![Screenshot 2024-03-28 224626](https://github.com/Glench/ExtPay/assets/66225070/0f057f88-1be9-4f75-9838-d3dcace33c0e)

**Comment by Glench** [comment]
OK, I'm going to close this until it can actually be verified. Feel free to comment when you have a minimal reproduction set up and I can re-open.
