### ISSUE TITLE
Starting trial in test mode but " user.trialStartedAt && (now - user.trialStartedAt) < sevenDays " false

### ISSUE THREAD

**Issue by adamstrad** [Glench/ExtPay#195]
problem was because you cannot use the test email for testing trial.

**Comment by adamstrad** [comment]
The problem seems to be that after starting the trial,  user.trialStartedAt = null

**Comment by animalnots** [comment]
Got the same issue, 
@adamstrad how did you resolve it?

**Comment by adamstrad** [comment]
hey @animalnots  it turned out that the problem was that I was testing it with my ExtPay account email address.
Each time I reloaded my app and tried to register for a trial, what was actually happening was I was logging in with a paid email address. The docs say this:

`While testing, use your ExtensionPay email to test payments without entering credit card information. Reinstall the extension to reset back to an unpaid user.`

I resolved it by using another email address, I was able to sign up for a free trial this way and it turned out it already worked fine.
