### ISSUE TITLE
ExtPay is not a function

### ISSUE THREAD

**Issue by uluhonolulu** [Glench/ExtPay#2]
I'm trying to use ExtPay as a module, but it says that it's not a function:
```
import ExtPay from 'extpay';
const extpay = ExtPay('detoxbox');
```
Actually, `ExtPay` is an object: `JSON.stringify(ExtPay)` returns `{}`.

What am I doing wrong?

**Comment by Glench** [comment]
How did you install ExtPay and how are you bundling? Would help to know which of the files in the `dist` folder it was using to track down the bug.

**Comment by uluhonolulu** [comment]
I installed it using `npm install`. I'm bundling using webpack, and it looks like a wrong file is picked indeed:

![image](https://user-images.githubusercontent.com/872764/108637859-3995cd80-7495-11eb-8859-67d8f5057f3a.png)

Here is a piece of my webpack.config.js that looks relevant:
```
  resolve: {
    extensions: ['.js', '.jsx', '.css'],
    modules: [path.resolve(__dirname, 'src'), 'node_modules'],
    alias: {
      react: 'preact/compat',
      'react-dom': 'preact/compat',
    },
  },
```

Hope that helps.

**Comment by uluhonolulu** [comment]
I also noticed that if I remove the `"browser": "./dist/ExtPay.js",` part from your package.json, then the correct file is packed. So it might be a webpack issue.

**Comment by Glench** [comment]
I'm not familiar with webpack so I'm not really sure how much I can help here. You definitely need to get webpack to choose the right module. You're right — it isn't choosing the right file. It looks like [this page on webpack config](https://webpack.js.org/configuration/resolve/) should shed light on the issue.

**Comment by Glench** [comment]
Cool, glad you got it working! I think you can use the webpack`alias` or [`mainFields`](https://webpack.js.org/configuration/resolve/#resolvemainfields) configurations to get it to work properly. I'm going close this issue since it doesn't seem like a strictly `ExtPay` issue but please keep me and this thread updated for future documentation!

**Comment by uluhonolulu** [comment]
@Glench yes, `mainFields` fixed it!

It turned out that if you don't set `target: "node"` in your webpack config, it assumes that you're building for the Web and checks the `browser` field first. Adding the part below to webpack config solved this for me:
```
  resolve: {
    mainFields: ['module', 'main'],
  },
```

**Comment by Glench** [comment]
Excellent, so glad to hear it's working for you! Thanks for updating the thread.

**Comment by GorvGoyl** [comment]
> @Glench yes, `mainFields` fixed it!
> 
> It turned out that if you don't set `target: "node"` in your webpack config, it assumes that you're building for the Web and checks the `browser` field first. Adding the part below to webpack config solved this for me:
> 
> ```
>   resolve: {
>     mainFields: ['module', 'main'],
>   },
> ```

was facing the same issue, and this worked.
