### ISSUE TITLE
Is Ext Pay down? My error: Uncaught (in promise) ExtPay error while fetching user: {"message":"Whoops! Server error. Please try again or contact the website developer.","type":"error","code":500}

### ISSUE THREAD

**Issue by quest4best** [Glench/ExtPay#203]
UPDATE: So I am able to use the Login Method where it sends a link to the email, but I am not able to sign in like I usually do. Only the login is working at this time. Is anyone else experiencing this?

After I log in with my info over test mode, I am getting this error:

 Uncaught (in promise) ExtPay error while fetching user: {"message":"Whoops! Server error. Please try again or contact the website developer.","type":"error","code":500}
 
 I have tried sever iterations of my extension, including older ones that did work just to make sure its not something  I changed in the code. Is there a chance the server is just down somehow?

**Comment by quest4best** [comment]
Not sure what happened, maybe it was just bad timing but after many small trial and error attempts, its now working again with no problem.

**Comment by Jatin-Lalit** [comment]
getting the same issue, can you please share how you resolved the same

**Comment by Glench** [comment]
Jatin, your issue is completely different to the parent issue. I addressed it in an email to you!

The short answer is that no, ExtPay is probably not down! We have 99.99% uptime :) Not sure what the original issue in this thread was, but it's clearly no longer an issue.
