### ISSUE TITLE
Trail users addition is NOT working

### ISSUE THREAD

**Issue by complanboy2** [Glench/ExtPay#209]
**Describe the bug**
When we add trial users, although we received a message saying "1 user added successfully.", the user(s) aren't showing on Free trial dashboard. Also when trying to get their state, the "trailStartsAt" is giving null value.

**To Reproduce**
1. Go to 'https://extensionpay.com/home/extension'
2. Click on 'Add free users'
3. Enter the email in text area and click "add users"
4. Go back and click the "free trial user dashboard"
5. Verify there are no users shown

**Expected behavior**
After trial users addition, they show up in in the dashboard

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
<img width="887" alt="Screenshot 2024-05-10 at 6 51 24 AM" src="https://github.com/Glench/ExtPay/assets/2462965/9ea37b66-ccee-449a-9ad4-6c465bd6b512">

**Comment by burkybang** [comment]
You’re adding lifetime subscription users who don't have to pay. You’re not adding free trial users. You cannot sign someone else up for a free trial.

**Comment by complanboy2** [comment]
Understand, so where can I see these lifetime free users? and is there a way that I delete them later or it's one time?

**Comment by burkybang** [comment]
You can't on your own. You'd have to email @Glench about either/both.

**Comment by Glench** [comment]
Yep, just email me to see the full list! Although we'll add a better UI for managing them yourself in the future.
