### ISSUE TITLE
extpay.openPaymentPage() opens a popup without indicating anything about security or location ...

### ISSUE THREAD

**Issue by escape75** [Glench/ExtPay#228]
Although technically not a bug, I'm wondering if anything can be done to assure the buyer that they are visiting a legitimate site ...

I've had someone contact me saying that they were unsure if this was served over https and where the popup was served from,
and of course they could perform a "view source code" on the popup to get that info, however I do get their point :)

**Comment by escape75** [comment]
One can adjust the code for open_popup to perform a window.open to correct this if needed …

**Comment by escape75** [comment]
Sounds great. Thank you for the update!

Yes I did close it after I realized one could just modify the popup code to
open the window with whatever UI features are required via window.open

Thanks!
Martin

**Comment by Glench** [comment]
Sure, but for you and anyone else — we really wouldn't recommend this approach! The popup page is not designed to be viewed full-screen and may change at any time, resulting in a less than ideal or even broken experience for your customers. If you want to take that risk that's up to you, but we only officially support the popup window at the moment.

**Comment by escape75** [comment]
Thanks for the suggestion!

Right now, I am simply modifying the open_popup code:

async function open_popup(url, width, height) {
    window.open(url, null,
`toolbar=no,location=no,directories=no,status=no,menubar=no,width=${width},height=${height},left=${(screen.width-width)/2},top=${(screen.height-height)/2}`);
}
