### ISSUE TITLE
Can't test real bank card payment in Dev mode

### ISSUE THREAD

**Issue by vatszdesign** [Glench/ExtPay#238]
**Describe the bug**
When I try to execute a payment with real bank card data in development mode locally, the ExtPay popup displays the message 'Please try again. Enable JavaScript if it is disabled.' under the bank card field. Is this behavior intentional, or would it still occur if the extension were published?

ExtPay works perfectly when I log in with my developer email, but this issue only appears when I try to make a regular payment in development mode.

**Expected behavior**
My expectation is that if I use an email address other than the one I registered with on extensionpay.com, I should be able to test a real transaction, which would also appear in Stripe, even in developer mode before publishing my extension.

**Screenshots**
![Screenshot 2024-09-11 at 21 05 35](https://github.com/user-attachments/assets/18c86ada-7f1c-480d-921f-83f72bbcb5e5)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave

**Comment by Glench** [comment]
Real or fake payments are not supported in test mode with ExtPay 3.0.
