### ISSUE TITLE
A network or server error occurred. 

### ISSUE THREAD

**Issue by vatszdesign** [Glench/ExtPay#240]
**Describe the bug**
I just recently published my extension to the Chrome Webstore and when I try to make a purchase the popup prompts the following error: "A network or server error occurred. Please try again." "Server error. Try your payment again."

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ExtPay popup
2. Enter email and bank data
3. Click the Subscribe button

**Expected behaviour**
It should make the purchase. In my bank app a popup appears: 'Focus Ex Subscription - Validation of bank cards' but in the ExtPay popup on my desktop screen the following screen is shown and no purchase is made.

**Screenshots**
![error extpay](https://github.com/user-attachments/assets/fe693233-f62a-41ee-b390-962399a26bf1)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Brave Browser 
 [Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (arm64)](https://brave.com/latest/)
 - Chrome Browser
Version 129.0.6668.60 (Official Build) (arm64)

**Additional context**
You can find and download and check my extension from:
https://chromewebstore.google.com/detail/focus-ex/dlchhkpnfagokiecakphcgilhgdimkkg

**Comment by vatszdesign** [comment]
I reconnected the extension profile in the ExtPay console to Stripe and now the purchase works properly. However, this way created a new Stripe account. Is it possible to reconnect to the previous Stripe account? Every time I connect to Stripe, it creates a new Stripe account for the extension.

**Comment by ruffin--** [comment]
Paging @Glench -- is this thing still on? Is @vatszdesign doing something wrong or ExtPay borked?

(Me: Prospective new user perusing github issues. I see some action on your [twitter timeline from last week](https://x.com/Glench/status/1861541502058471874) but not sure if this lib is still going or not.)

**Comment by Glench** [comment]
Either it was a transient error or there was something misconfigured with your Stripe account. If you see this error in development mode that's because payments don't work in dev mode — only in production mode.
