### ISSUE TITLE
Error on trial pop up

### ISSUE THREAD

**Issue by duroshub** [Glench/ExtPay#26]
Hi there,
I have implemented everything fine so far but when I add a button to activate trial period I have 2 problems:

- in the pop up no matter what email I insert it keeps say to me "Please provide a valid email" when I push Strat Trial
- when I implement the button trial when I push the icon of the extension automatically opens trial pop up and It do not show the two choices

\\popup.html
_<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" href="https://unpkg.com/mvp.css">
    </head>
    <body>
        <header>
            <h1 style="width: 400px">ExtensionPay.com Sample Extension</h1>
            <p style="font-size: 1.2rem;">User hasn't paid :(</p>
            <button>Pay now</button>
			<button type="submit">Start 3 days trial</button>
        </header>
        <script src="ExtPay.js"></script>
        <script src="popup.js"></script>
    </body>
</html>_

\\popupjs

_const extpay = ExtPay('************') 

document.querySelector('button').addEventListener('click', extpay.openPaymentPage)

document.querySelectorAll('button[type=submit]').addEventListener('click', extpay.openTrialPage('3-days'))

extpay.getUser().then(user => {
    const now = new Date();
    const sevenDays = 1000*60*60*24*3 // in milliseconds
    if (user.trialStartedAt && (now - user.trialStartedAt) < sevenDays) {
                  document.querySelector('p').innerHTML = 'Enjoy your trial period 🎉'
                  document.querySelector('.trialone').remove()
    } else {
				if (user.paid) {
				document.querySelector('p').innerHTML = 'User has paid! 🎉'
				document.querySelector('button').remove()
				}
    }
})_

   Thanks in advance

**Comment by duroshub** [comment]
This is popup.html

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" href="https://unpkg.com/mvp.css">
    </head>
    <body>
        <header>
            <h1 style="width: 400px">ExtensionPay.com Sample Extension</h1>
            <p style="font-size: 1.2rem;">User hasn't paid :(</p>
            <button>Pay now</button>
			<button type="submit">Start 3 days trial</button>
        </header>
        <script src="ExtPay.js"></script>
        <script src="popup.js"></script>
    </body>
</html>

**Comment by duroshub** [comment]
This is popup.html

`<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" href="https://unpkg.com/mvp.css">
    </head>
    <body>
        <header>
            <h1 style="width: 400px">ExtensionPay.com Sample Extension</h1>
            <p style="font-size: 1.2rem;">User hasn't paid :(</p>
            <button>Pay now</button>
			<button type="submit">Start 3 days trial</button>
        </header>
        <script src="ExtPay.js"></script>
        <script src="popup.js"></script>
    </body>
</html>`

**Comment by duroshub** [comment]
This is popup.htm
![popup](https://user-images.githubusercontent.com/103271999/162478377-5ecec2b2-0de0-4d80-b2d0-9451c3fd5b08.png)
l

**Comment by Glench** [comment]
>in the pop up no matter what email I insert it keeps say to me "Please provide a valid email" when I push Strat Trial

I can't reproduce this problem. First try uninstalling and reinstalling your extension. If it still happens, please post a screenshot and paste the JS console output from the trial page.

> when I implement the button trial when I push the icon of the extension automatically opens trial pop up and It do not show the two choices

This is because of this line:

```js
document.querySelectorAll('button[type=submit]').addEventListener('click', extpay.openTrialPage('3-days'))
```



That line actually calls the extpay.openTrialPage function on page load, not on click as you intended.

It should be:

```js
function openTrial() {
  extpay.openTrialPage('3-day');
}
document.querySelectorAll('button[type=submit]').addEventListener('click', openTrial)
```

**Comment by duroshub** [comment]
Thank you Glench pop up now works like a charm.

I still receive error when I put any email on Trial page.

The console output is this one:

Alcuni cookie utilizzano l’attributo “SameSite“ consigliato in modo non corretto 3
Il cookie “_ga_VSSRYC7YY5” verrà presto rifiutato in quanto l’attributo “SameSite” è impostato a “None” o un valore non valido, senza l’attributo “secure”. Per ulteriori informazioni sull’attributo “SameSite”, consultare https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [js:145:1625](https://www.googletagmanager.com/gtag/js?id=G-VSSRYC7YY5)
Il cookie “_ga” verrà presto rifiutato in quanto l’attributo “SameSite” è impostato a “None” o un valore non valido, senza l’attributo “secure”. Per ulteriori informazioni sull’attributo “SameSite”, consultare https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [js:145:1625](https://www.googletagmanager.com/gtag/js?id=G-VSSRYC7YY5)
Il cookie “_ga_VSSRYC7YY5” verrà presto rifiutato in quanto l’attributo “SameSite” è impostato a “None” o un valore non valido, senza l’attributo “secure”. Per ulteriori informazioni sull’attributo “SameSite”, consultare https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [js:145:1625](https://www.googletagmanager.com/gtag/js?id=G-VSSRYC7YY5)
Response { type: "basic", url: "https://extensionpay.com/extension/ai-bot-4-instagram/trial?api_key=1142e996-da73-486f-bfcc-12b8d6b377fe&period=3-day", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, body: ReadableStream, bodyUsed: false }
​
body: ReadableStream { locked: true }
​​
locked: true
​​
<prototype>: ReadableStreamPrototype { cancel: cancel(), getReader: getReader(), tee: tee(), … }
​​​
cancel: function cancel()
​​​​
length: 0
​​​​
name: "cancel"
​​​​
<prototype>: function ()
​​​
constructor: function ()
​​​
getReader: function getReader()
​​​
locked: 
​​​
tee: function tee()
​​​
Symbol(Symbol.toStringTag): "ReadableStream"
​​​
<get locked()>: function locked()
​​​
<prototype>: Object { … }
​
bodyUsed: true
​
headers: Headers {  }
​​
<prototype>: HeadersPrototype { append: append(), delete: delete(), get: get(), … }
​
ok: true
​
redirected: false
​
status: 200
​
statusText: "OK"
​
type: "basic"
​
url: "https://extensionpay.com/extension/ai-bot-4-instagram/trial?api_key=1142e996-da73-486f-bfcc-12b8d6b377fe&period=3-day"
​
<prototype>: ResponsePrototype { clone: clone(), arrayBuffer: arrayBuffer(), blob: blob(), … }
​​
arrayBuffer: function arrayBuffer()
​​
blob: function blob()
​​
body: 
​​
bodyUsed: 
​​
clone: function clone()
​​
constructor: function ()
​​
formData: function formData()
​​
headers: 
​​
json: function json()
​​
ok: 
​​
redirected: 
​​
status: 
​​
statusText: 
​​
text: function text()
​​
type: 
​​
url: 
​​
Symbol(Symbol.toStringTag): "Response"
​​
<get body()>: function body()
​​
<get bodyUsed()>: function bodyUsed()
​​
<get headers()>: function headers()
​​
<get ok()>: function ok()
​​
<get redirected()>: function redirected()
​​
<get status()>: function status()
​​
<get statusText()>: function statusText()
​​
<get type()>: function type()
​​
<get url()>: function url()
​​
<prototype>: Object { … }
 true [all.js:64:17](https://extensionpay.com/static/js/all.js?cache=37711aff-ebd5-4be3-ba7f-36f43a608b55)
![Immagine 2022-04-13 102353](https://user-images.githubusercontent.com/103271999/163133680-3baf4228-170b-41a7-ae17-119ea018db73.png)

**Comment by Glench** [comment]
Ah, you found a race condition! Thanks for reporting the bug — it has been fixed and should work just fine now.

**Comment by duroshub** [comment]
Thank you,

but know when I click on start trail it says " an email was sento to glen@extensionpay.com" and also when I click Pay Now the form is pre filled with glen@extensionpay.com.

Let me know.

Thanks in advance.

**Comment by Glench** [comment]
That's because I tested with your URL. Just uninstall and reinstall the extension to reset.

**Comment by duroshub** [comment]
I've tried but nothing change. I have also pushed a new version of the app but "same problem".

**Comment by Glench** [comment]
What is the URL of the trial popup?

**Comment by duroshub** [comment]
In manifest I've:
      "browser_action": {
        "default_popup": "popup.html"
    }

popup.html is in the root.

Thanks in advance.

**Comment by Glench** [comment]
No, I mean the extensionpay url. It should be something like https://extensionpay.com/extension/[slug]?api_key=[key] . You can look in the console for if the URL bar doesn't show up.

**Comment by duroshub** [comment]
Ah ok!

TRIAL PAGE https://extensionpay.com/extension/ai-bot-4-instagram/trial?api_key=1142e996-da73-486f-bfcc-12b8d6b377fe&period=3-day

PAYMENT PAGE https://extensionpay.com/extension/ai-bot-4-instagram?api_key=1142e996-da73-486f-bfcc-12b8d6b377fe

**Comment by Glench** [comment]
Ah, if that's the case then yes, I believe you didn't fully uninstall and reinstall your extension in your browser.
