### ISSUE TITLE
Unable to Initalize ExtPay

### ISSUE THREAD

**Issue by Arjun-Sharma1** [Glench/ExtPay#4]
Getting an error when trying to initialize ExtPay. I followed the instructions to integrate it and I'm using the latest version. Let me know if i'm doing something wrong. Using Google Chrome as the browser.

![f6e2716e0dbff2fc5064ee8c1a02f43f](https://user-images.githubusercontent.com/17027141/109362625-65c89a00-7859-11eb-9006-ebb74a7455de.png)
I tried commenting that block of code out which works but it gives an error when I call extpay.openPaymentPage(). I think it's related to the browserPolyfill not being initialized properly.

This is my manifest.json.
![6850e067cea6b6711d98f7b73b68d36d](https://user-images.githubusercontent.com/17027141/109362705-927cb180-7859-11eb-8c0e-722d40ab9259.png)

Background.js
![79dc71933735061291e5c4c3ed50795a](https://user-images.githubusercontent.com/17027141/109363540-d328fa80-785a-11eb-8db1-276eb1973b0c.png)

**Comment by Glench** [comment]
I was able to reproduce this and pushed a fix here and to npm. Please let me know if this fixes it. Thanks for the bug report!

**Comment by Arjun-Sharma1** [comment]
It no longer gives me an error on that line anymore but now I'm facing an error calling the openPaymentPage method.

![a4b8d638e867532388c1f5b564e816d7](https://user-images.githubusercontent.com/17027141/109367771-02446980-7865-11eb-9cba-94b2111e7103.png)

**Comment by Glench** [comment]
Wow you're finding all the bugs! Sorry about that. I just pushed a fix for the popup bug, 2.0.3. Mentioning it here for reference: https://github.com/Glench/ExtPay/commit/b23f26a16887444f6fcb6569cc4ee01dd6d68602
