### ISSUE TITLE
Importing ExtPay does not work with Webpack

### ISSUE THREAD

**Issue by henrikra** [Glench/ExtPay#41]
**Describe the bug**

I have a working Chrome extension which uses TypeScript and it makes the build with Webpack. But unfortunately when I am following the instructions of ExtPay I cannot import the `ExtPay` function in any way. Below there are two things I have tried:

```ts
// in background script file

import ExtPay from 'extpay';
const extpay = ExtPay('sample-extension');
```

Error you will get in this case
```
Uncaught TypeError: extpay__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function
```

According to the TypeScript types that this library provides this should be correct but still it doesn't work.

Then I tried another way shown in the README without any luck.

```ts
// in background script file

import 'ExtPay'
const extpay = ExtPay('sample-extension');
```
Error you will get
```
Uncaught ReferenceError: ExtPay is not defined
```

So I guess ExtPay tries to expose global object without being succesful. What is the reason to use globals in the first place? :P Usually they make things more complicated.

**To Reproduce**
Have a Chrome extension project with Webpack build and see it failing

So am I missing something from the docs or does this thing work with Webpack builds?

**Comment by Glench** [comment]
Can you please create an example repo that shows this happening with what commands to run? I'm not very familiar with webpack.

**Comment by henrikra** [comment]
Sure here is example repo I did: https://github.com/henrikra/demo-extpay-webpack-problem

1. `npm install`
2. `npm run build` to make compiled JavaScript
3. Go to `chrome://extensions/` and load the `dist` folder as unpacked extension

You will instantly error saying that the the imported values from `extpay` is not function.

Hope you can see the problem now 👍

**Comment by henrikra** [comment]
@Glench Please try again. I accidentally put `manifest.json` to `.gitignore`. Pull the changes and try again 👍

**Comment by doriandrn** [comment]
Hey there,

I had the same issue and upon checking the code in the "dist" dir, it seems there is no export defined for the main extpay js file.

A quick workaround to make this work is to import the .module file which has an export.

```import ExtPay from 'extpay/dist/ExtPay.module'```

**Comment by Glench** [comment]
So yeah, this is a configuration error with your webpack config. By default webpack tries to resolve libraries by their package.json's fields in this order: `['browser', 'module', 'main']` ([source](https://webpack.js.org/configuration/resolve/#resolvemainfields)). If you want to use import, you want to do something like this instead:

webpack.config.js
```js
module.exports = {
  //...
  resolve: {
    mainFields: ['module', 'main'],
  },
};
```

Does anyone know how other libraries do this? If there's a way I can make ExtPay work with webpack's default settings that would probably reduce a lot of confusion.

**Comment by henrikra** [comment]
I think this is your problem. You should not distribute browser variant of ExtPay with npm package release. The browser field is pointing to the global version of ExtPay:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/12229968/177870659-82ccbd67-e01d-4f37-85ce-2f4ee076c8bd.png">

**Comment by Glench** [comment]
> I think this is your problem. You should not distribute browser variant of ExtPay with npm package release. The browser field is pointing to the global version of ExtPay:

Hm, I don't know. In the [package.json docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#browser) it says to define `browser` if your library is meant to be used client-side, which obviously this library is, which means it shouldn't have exports/imports. So it seems like kind of a case between what package.json defines and what webpack does by default. Confusing and I'm not sure what to do here if anything. I'm open to suggestions.

Regardless, there are multiple fixes for the problem in this thread so I may end up closing it.

**Comment by henrikra** [comment]
If check any other libraries inside of `node_modules` you can see that they don't use `browser` field in their `package.json` for this exact reason. Here is example of famous `data-fns` library (https://github.com/date-fns/date-fns) inside of my project and it doesn't have `browser` field. It has only `main` which is the correct way 👍 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/12229968/177936053-897a5add-52b6-4acb-b24a-2c4146e3d04a.png">

**Comment by henrikra** [comment]
Another big library called Vue (https://github.com/vuejs/vue) does not use `browser` field even though it is meant for browser:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/12229968/177936628-fc4bbaa1-c379-4dc7-8efe-1f44a0a71764.png">


So I would say it is very clear that the `browser` field should not be used

**Comment by henrikra** [comment]
@doriandrn and @Glench Can you test out the PR I did to fix this issue? https://github.com/Glench/ExtPay/pull/42

**Comment by Glench** [comment]
OK cool, thanks for finding examples and for the PR. I guess if possible I want to make sure that this change, which as far as I know seems to only impact webpack, doesn't break other build systems. Do you know any other resources on the "browser" field and can you explain where the discrepancy is between the official package.json docs and webpack's implementation?

**Comment by henrikra** [comment]
What discrepancy do you mean?

Btw check the PR, I added also a comment there 👍

**Comment by Glench** [comment]
The discrepancy between package.json saying to use the browser field for browser-based libraries and webpack failing to import a library using globals that's meant for the browser.

For now I'm just going to say YOLO and merge the change and we'll see if it breaks any other build systems.

**Comment by henrikra** [comment]
Just tested the new release and works like a charm!
