### ISSUE TITLE
Switching to production

### ISSUE THREAD

**Issue by uluhonolulu** [Glench/ExtPay#5]
How do I switch to production? I've installed my extension from Chrome Store, but I'm still seeing the payment popup in Test mode.

**Comment by Glench** [comment]
Hm, I just installed your extension and it seems to be working just fine:

![Screen Shot 2021-03-09 at 11 02 51 AM](https://user-images.githubusercontent.com/451461/110500248-ffe4d980-80c6-11eb-9061-8a0a7f2d3ff2.png)

**Comment by uluhonolulu** [comment]
Uninstalled and installed again, now everything's fine. Weird.

**Comment by Glench** [comment]
Yeah! Please let me know if something like that happens again.
