### ISSUE TITLE
Newest Release not on NPM 

### ISSUE THREAD

**Issue by surtic86** [Glench/ExtPay#51]
Hi there,

I wanted to Update your Library to use the new Method "openLoginPage". But the Package is not available in the newest Version 3.0.3. 

[openLoginPage](https://www.npmjs.com/package/extpay)

Thanks

**Comment by Glench** [comment]
Thanks for finding this!

I just did an npm publish now and got an email from npm saying it's updated, but it isn't updating on the npm website. I sent a support question in and will update once I get a response.

**Comment by Glench** [comment]
Alright, site just updated, must have been on a delay. All set!

**Comment by surtic86** [comment]
perfect thanks
