### ISSUE TITLE
Make payment popup open near middle of window if possible

### ISSUE THREAD

**Issue by Glench** [Glench/ExtPay#6]
Right now the popup can show up in kind of a weird place on bigger screens: 

![Screen Shot 2021-03-09 at 11 06 04 AM](https://user-images.githubusercontent.com/451461/110500670-7255b980-80c7-11eb-8c46-ea97b8a6466c.png)

**Comment by ByBilal** [comment]
any update on this issue?

**Comment by Glench** [comment]
It hasn't been a priority yet. Is this something you're running into?

**Comment by Glench** [comment]
@ByBilal just checking in again, is this something you're running into?

**Comment by henrikra** [comment]
This is possible with simple math. Check this link https://stackoverflow.com/questions/5345435/pop-up-window-center-screen

Would be very beneficial and easy to implement 👍

**Comment by burkybang** [comment]
@henrikra Can confirm. That's exactly how I handled this too.
