### ISSUE TITLE
openPaymentPage not working

### ISSUE THREAD

**Issue by Arjun-Sharma1** [Glench/ExtPay#7]
It was working fine but after testing it with my developer credentials it just stopped working. Tried clearing chrome storage and cache but still getting this error.

![e2fd418027c18ff2fb30480b94366b02](https://user-images.githubusercontent.com/17027141/112761634-26ad7600-8fca-11eb-9b32-9ccf18caa923.png)

**Comment by Glench** [comment]
Hey sorry about that! Just to confirm, is that an error from a content script?

**Comment by Arjun-Sharma1** [comment]
Yeah I have a content script that inserts a button into the dom and when that button is pressed, it should open up the payment page. When the button is pressed it gets that error. It was working fine but not sure what happened recently.

**Comment by Glench** [comment]
Hm did you update ExtPay recently?

**Comment by Arjun-Sharma1** [comment]
Yeah I'm using the latest version right now

**Comment by Glench** [comment]
Try again with the release I just out: ExtPay 2.1.1 should fix the issue.

**Comment by Arjun-Sharma1** [comment]
Thanks its fixed
