### ISSUE TITLE
Make  "run_at: document_start" as optional

### ISSUE THREAD

**Issue by GorvGoyl** [Glench/ExtPay#8]
My extension breaks if I set `"run_at": "document_start"` but it seems like ExtPay requires this to be in manifest. If I don't use it, I get the following console error:
```
Uncaught (in promise) ExtPay setup error: Please make sure the ExtPay content script in your manifest.json runs at document start. You can copy the example below into your manifest.json or check the docs: https://github.com/Glench/ExtPay#2-configure-your-manifestjson

"content_scripts": [
        {
    "matches": ["https://extensionpay.com/*"],
    "js": ["ExtPay.js"],
    "run_at": "document_start"
}]
```
 Is it really required to use `"run_at": "document_start"` for ExtPay?

Moreover, Google suggest to not use `"run_at": "document_start"`  for performance reasons as mentioned in the [docs](https://developer.chrome.com/docs/extensions/mv2/content_scripts/#run_time)

> Use "document_idle" whenever possible. The browser chooses a time to inject scripts between "document_end" and immediately after the windowonload event fires. The exact moment of injection depends on how complex the document is and how long it is taking to load, and is optimized for page load speed.

**Comment by Glench** [comment]
The short answer is yes, the ExtPay content script needs to run at document_start for the `onPaid` event listener to work.

But here's what I would do for your extension. Have two separate content scripts, one for just ExtPay and one for everything else:

```js
"content_scripts": [
        {
    "matches": ["https://extensionpay.com/*"],
    "js": ["ExtPay.js"],
    "run_at": "document_start"
}, {
    "matches": ["https://notion.so/*"],
    "js": ["notionBoost.js"],
}]
```

You should still be able to include ExtPay in your notionBoost script without any problems.

**Comment by GorvGoyl** [comment]
didn't know we could do this way.
Since, i'm using webpack bundler which merges ExtPay.js into `background.js` file. So, I guess I need to add background.js file instead:

```
"content_scripts": [
    {
      "matches": ["*://*.notion.so/*"],
      "js": ["content.bundle.js"]
    },
    {
      "matches": ["https://extensionpay.com/*"],
      "run_at": "document_start",
      "js": ["background.bundle.js"]
    }
  ],
```

**Comment by Glench** [comment]
Yeah! Or you could create a new file that just includes ExtPay (`const ExtPay = require('extpay')` or however you import modules) and make your bundler spit that out. Let me know if everything is working okay.

**Comment by GorvGoyl** [comment]
This is working fine, thanks!

**Comment by Glench** [comment]
awesome!
