### ISSUE TITLE
`openLoginPage` not part of types declaration

### ISSUE THREAD

**Issue by ba32107** [Glench/ExtPay#80]
**Describe the bug**
Not a real bug, but the `openLoginPage` function is not among the typescript declarations.

**To Reproduce**
1. Create a typescript project
2. Attempt to use the function
3. Observe error

**Expected behavior**
[Typescript declarations](https://github.com/Glench/ExtPay/blob/main/types.d.ts) contain the function

**Additional context**
I would open a PR to fix, but not sure if any other change is needed!

**Comment by Glench** [comment]
Fixed in 064b04a
